# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "701d1cbdbffe22c3cfaa89985d7235be"
name = "PrizePop"
application_url = "https://prizepop.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_app_proxy,write_products"

[auth]
redirect_urls = [
  "https://prizepop.onrender.com/api/auth/callback",
  "https://prizepop.onrender.com/api/auth/oauth/callback",
]

[app_proxy]
url = "https://prizepop.onrender.com/redeem"
prefix = "apps"
subpath = "redeem"

[access.admin]
direct_api_mode = "online"